blank_issues_enabled: false
contact_links:
  - name: Bug Report
    about: Please ask and answer questions here.
  - name: New Feature
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
