blank_issues_enabled: false
contact_links:
  - name: Bug Report
    title: "[Bug]: "
    about: Template for bugs.
  - name: New Feature
    title: "[Feature]: "
    about: Please report security vulnerabilities here.
